# Basic configuration for Just the Docs
# bundle exec jekyll serve

# For MathJax/LaTeX, add a supplementary configuration, e.g.:
# bundle exec jekyll serve --config _config.yml,_mathjax_svg.yml

title: CBS-LaTeX
email: plancomps@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site illustrates how CBS specifications of languages and funcons could be
  formatted for the web using LaTeX, Markdown, and MathJax. One of the aims is
  for CBS on web pages look like the CBS in published papers, using mathematical
  symbols instead of plain text.
baseurl: "/cbs-latex" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  plancomps-admin

# Build settings
remote_theme: pdmosses/just-the-docs@pages-and-collections
plugins:
  # - jekyll-feed
  - jekyll-remote-theme
  
defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Aux links for the upper right navigation
aux_links:
  "CBS LaTeX on GitHub":
    - "//github.com/plancomps/cbs-latex"

compress_html:
  blanklines: true
  # ignore:
  #   envs: all

color_scheme: light
